// pages/about.tsx
import * as React from "react";
import type { NextPage } from "next";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Link from "../src/Link";
import ProTip from "../src/ProTip";
import Copyright from "../src/Copyright";

const About: NextPage = () => {
    return (
        <Container maxWidth="lg">
            <Box
                sx={{
                    my: 4,
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    alignItems: "center",
                }}
            >
                <h1>About Sultans of Stats</h1>
                <p>
                    Sultans of Stats is a 4-division fantasy baseball superleague with yearly relegation based on individual league and
                    overall division standings hosted on{" "}
                    <a href="https://fleaflicker.com/" target="_blank">
                        Fleaflicker
                    </a>
                    . The best places to start learning more are the{" "}
                    <a href="https://www.reddit.com/r/SultansOfStats/" target="_blank">
                        subreddit
                    </a>{" "}
                    and/or the{" "}
                    <a href="https://discord.gg/hkCQabyaDn" target="_blank">
                        Discord
                    </a>
                    .
                </p>
                <p>
                    This website is intended to serve as a central hub of information as well as a historical archive of all things SoS. If
                    you're handy with the beep boops, please feel free to contribute to the site via{" "}
                    <a href="https://github.com/danhogan/sultansofstats" target="_blank">
                        Github
                    </a>
                    .
                </p>
            </Box>
        </Container>
    );
};

export default About;

// src/routes/about/+page.svelte
<div class="container about">
	<h1>About Sultans of Stats</h1>

	<p>
		Sultans of Stats is a 4-division fantasy baseball superleague with yearly relegation based on
		individual league and overall division standings hosted on
		<a href="https://www.fantrax.com/" target="_blank">Fantrax</a>. The best places to start
		learning more are the
		<a href="https://www.reddit.com/r/SultansOfStats/" target="_blank">subreddit</a> and/or the
		<a href="https://discord.gg/hkCQabyaDn" target="_blank">Discord</a>.
	</p>

	<p>
		This website is intended to serve as a central hub of information as well as a historical
		archive of all things SoS. If you're handy with the beep boops, please feel free to contribute
		to the site via
		<a href="https://github.com/danhogan/sultansofstats" target="_blank">Github</a>.
	</p>
</div>

<style>
	.about {
		margin-top: 2em;
		display: flex;
		flex-direction: column;
		align-items: center;
		text-align: center;
		max-width: 800px;
		margin-left: auto;
		margin-right: auto;
	}

	p {
		max-width: 65ch;
		line-height: 1.6;
	}
</style>
