// components/LineChart.tsx
import dynamic from "next/dynamic";

const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

export default function LineChart(props: any) {
    const series = [
        {
            name: "Guests",
            data: [19, 22, 20, 26],
        },
        {
            name: "Subs",
            data: [103, 105, 98, 83],
        },
    ];
    const options = {
        colors: [
            "#3D44CA",
            "#CA3D3D",
            "#E0CF42",
            "#59DB3F",
            "#E5AF34",
            "#AA50E1",
            "#A07C35",
            "#DF67D4",
            "#a9ed87",
            "#E5E5E5",
            "#979797",
            "#aaffc3",
            "#5DC3C2",
            "#90cde0",
            "#3ff527",
            "#f52727",
        ],
        xaxis: {
            title: {
                text: "Day",
            },
        },
        yaxis: {
            // title: {
            //     text: "Amount",
            // },
            labels: {
                formatter(val: any) {
                    if (["ERA", "WHP", "OBP", "OPS"].includes(props.selectedStat)) {
                        return parseFloat(val).toFixed(4);
                    } else {
                        return parseFloat(val).toFixed(0);
                    }
                },
            },
        },
        tooltip: {
            theme: "dark",
        },
        chart: {
            foreColor: "#BBB",
        },
        // markers: {
        //     size: 3,
        // },
    };

    return <Chart type="line" series={props.data} options={options} />;
}

// src/lib/components/LineChart.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let { data, selectedStat }: { data: any[]; selectedStat: string } = $props();

	let el: HTMLDivElement;
	let chart: any = null;

	function buildOptions() {
		return {
			colors: [
				'#3D44CA',
				'#CA3D3D',
				'#E0CF42',
				'#59DB3F',
				'#E5AF34',
				'#AA50E1',
				'#A07C35',
				'#DF67D4',
				'#a9ed87',
				'#E5E5E5',
				'#979797',
				'#aaffc3',
				'#5DC3C2',
				'#90cde0',
				'#3ff527',
				'#f52727'
			],
			series: data,
			chart: {
				type: 'line' as const,
				foreColor: '#BBB',
				background: 'transparent'
			},
			xaxis: {
				title: { text: 'Day' }
			},
			yaxis: {
				labels: {
					formatter(val: any) {
						if (['ERA', 'WHP', 'OBP', 'OPS'].includes(selectedStat)) {
							return parseFloat(val).toFixed(4);
						}
						return parseFloat(val).toFixed(0);
					}
				}
			},
			tooltip: { theme: 'dark' },
			theme: { mode: 'dark' as const }
		};
	}

	onMount(async () => {
		// Dynamic import prevents apexcharts from running during SSR/prerender
		const ApexCharts = (await import('apexcharts')).default;
		chart = new ApexCharts(el, buildOptions());
		chart.render();
		return () => chart?.destroy();
	});

	$effect(() => {
		if (chart) {
			chart.updateOptions(buildOptions(), true, true);
		}
	});
</script>

<div bind:this={el}></div>
